# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb743515866f8bfb869c18241902373f961cc434ebbb8b714fe16c39b3373c2a061994af3d6150cf924a784547f0bb2ce56249d039d37032eb1635fdf642f276

test:
  secret_key_base: ffbb767d29e46420230a8cef7dc054eefcb826ef912172de576f258a1a86c5c338151eb2627d6b8304dec95c1e5ffd2215c710153a8a60320a380aaec5e2907a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
